[package]
name = "resonanz-egui-simple-template"
version = "0.1.0"
edition = "2021"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
rust-version = "1.82"
publish = false

[dependencies]
eframe = "0.29.1"
